CREATE DATABASE MyRestfullApp;

CREATE TABLE users (
	id INT IDENTITY PRIMARY KEY,
	nombre NVARCHAR(100) NOT NULL,
	apellido NVARCHAR(100) NOT NULL,
	email NVARCHAR(100) NOT NULL,
	pass NVARCHAR(20) NOT NULL
);